services:
  # --- Workers for `s3-upload` ----------------------

  celery-s3-upload-worker-1:
    image: tvorchalavka/file-uploader:latest
    container_name: celery-s3-upload-worker-1
    command: /scripts/entrypoint.py --worker s3-upload
    env_file: ../.env
    restart: always
    networks:
      - tvorcha-network
    volumes:
      - tvorcha-efs:/mnt/efs
    mem_limit: 512m
    cpus: 1

  # --- Workers for `db-upload` ----------------------

  celery-db-upload-worker-1:
    image: tvorchalavka/file-uploader:latest
    container_name: celery-db-upload-worker-1
    command: /scripts/entrypoint.py --worker db-upload
    env_file: ../.env
    restart: always
    networks:
      - tvorcha-network
    volumes:
      - tvorcha-efs:/mnt/efs
    mem_limit: 512m
    cpus: 1


networks:
  tvorcha-network:
    external: true

volumes:
  tvorcha-efs:
    external: true
